spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondhanddb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:   
      hibernate:
        format_sql: true
server:
  port: 8081
